---
# ##[ Create Disk Partitions ]##################################################

- name: Create Disk Partitions Block
  when:
    ansible_nodename != "localhost"
  tags:
    - create_partitions

  block:
    # This is created for UEFI booting
    - name: Create UEFI Boot Loader Partitions
      ansible.builtin.command:
        cmd: "sgdisk {{ uefi_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"

    # 1 or 2 devices = single or mirror flags, 3 or more use raid flags
    - name: Create SWAP Partitions
      ansible.builtin.command:
        cmd: "sgdisk {{ (disk_by_id | length | int > 2) | ternary(raidz_multi_disk_swap_flags, single_disk_or_mirror_swap_flags) }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"
      when:
        - enable_swap_partitions | default(true) | bool

    - name: Create Root Pool Partitions
      ansible.builtin.command:
        cmd: "sgdisk {{ root_partition_flags }} {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ disk_by_id }}"

    - name: Pause for 5 seconds to settle
      ansible.builtin.pause:
        seconds: 5

    - name: Notify Kernel of Updated Partitions
      ansible.builtin.command:
        cmd: "partprobe"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      when:
        - not disable_partprobe | default(false) | bool

###############################################################################
