---
# [ Install ZFS ]##############################################################
- name: Install ZFS into chroot Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_zfs
  block:
    - name: Run chroot command for apt update
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c 'apt-get -qq update'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      when:
        - ansible_os_family == "Debian"

    - name: Install ZFS into chroot
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "apt install --yes --no-install-recommends software-properties-common debconf-utils"
        - "apt install --yes --no-install-recommends linux-generic linux-headers-generic linux-image-generic"
        - "apt install --yes --no-install-recommends wget nano vim"
        - "apt install --yes --no-install-recommends zfsutils-linux zfs-zed zfs-initramfs"
      when:
        - ansible_os_family == "Debian"

    # The "old" kernel links mess up zfsbootmenu generation, so remove them
    # Don't need them for an initial install anyway
    - name: Clean up old kernel links
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "{{ live_cd_mountpoint }}/boot/vmlinuz.old"
        - "{{ live_cd_mountpoint }}/boot/initrd.img.old"

    - name: Ensure cachefile exists and zfs-import-cache is active
      ansible.builtin.command:
        cmd: "{{ chroot_cmd }} bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "zpool set cachefile=/etc/zfs/zpool.cache {{ root_pool_name }}"
        - "systemctl enable zfs.target zfs-import-cache zfs-mount zfs-import.target"
