---
# [ Unmount chroot ]###########################################################
- name: Prepare for First Reboot Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - unmount_chroot
  block:
  # Issue trying to get everything unmounted cleanly
  # https://github.com/openzfs/openzfs-docs/issues/270
    - name: Unmount chroot file systems
      ansible.builtin.shell: |
        zfs umount -a
        mount | grep -v zfs | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}
        umount /mnt/*
        umount -R /mnt
        umount -l /mnt
        grep /mnt /proc*/mounts | tac | awk '{print $3}' FS="/" | uniq | xargs -i{} kill -9 {}

        ZFSBUILD_C=$(echo {{ live_cd_mountpoint }} | sed -e 's!/!\\/!'g)
        mount | grep -v zfs | tac | awk '/${ZFSBUILD_C}/ {print $3}' | xargs -i{} umount -lf {}
      register: cmd_output
      changed_when: cmd_output.rc == 0
      ignore_errors: true

    - name: Export all ZFS Pools
      ansible.builtin.command:
        cmd: "zpool export -a"
      register: cmd_output
      changed_when: cmd_output.rc == 0
