---
# [ Final Reboot of Remote System ]###########################################
- name: Final Reboot of Remote System Block
  tags:
    - restart_remote_final
  block:
    - name: Final Remote Restart
      ansible.builtin.pause: # noqa yaml[line-length]
        prompt: |

          ##########################################################
          # {{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }} will be rebooted.
          ##########################################################

          {% if root_pool_encryption | default(false) | bool %}When prompted for passphrase for '{{ root_pool_name }}', use: {{ (no_log_secrets | default(true)) | ternary("**********", passphrase) }}
          {% endif %}

          Press ENTER to reboot:

          * Root password is now disabled.
          * Ansible password is disabled, only SSH key connection allowed.
          * ZFS Snapshots for apt and dpkg are enabled.
          * ZFS snapshot for base installation "@base_install" created.

          {% if enable_dropbear_support | bool %}
          * Dropbear has been installed and configured, example connection:
            ssh -i ~/.ssh/<public_key> -p 222 {{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}
          {% endif %}

            NOTE: You will likely have to remove "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}" from your ~/.ssh/known_hosts

          Press ENTER to reboot {{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}

    - name: Commencing Reboot, will take a few minutes....
      ansible.builtin.reboot:
        pre_reboot_delay: 30
        reboot_timeout: 3600

###############################################################################
